name: Track Positions

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:        # Allow manual runs from the GitHub UI

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust as needed

      # Cache active_positions.json file
      - name: Restore cached positions file
        id: cache-positions
        uses: actions/cache@v4
        with:
          path: active_positions.json
          key: active-positions-${{ runner.os }}-${{ github.sha }}  # Unique key for the cache
          restore-keys: |
            active-positions-${{ runner.os }}-

      - name: Run tracking script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python track_positions.py

      # Save updated positions file back to cache
      - name: Cache updated positions file
        uses: actions/cache@v4
        with:
          path: active_positions.json
          key: active-positions-${{ runner.os }}-${{ github.sha }}  # Same key used during restore
