name: Track Positions

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:        # Allow manual runs from the GitHub UI

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust as needed

      - name: Download last known positions
        uses: actions/download-artifact@v4
        with:
          name: active-positions
          path: .

      - name: Run tracking script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python track_positions.py

      - name: Upload updated positions
        uses: actions/upload-artifact@v4
        with:
          name: active-positions
          path: active_positions.json
